# Class

### Class의 상속

In [2]:
#사칙연산을 하는 클래스
# => 클래스 이름, 변수, 함수(메서드), 초기화 함수(생성자)
#클래스의 이름 대문자로 시작 => FourCal 
# 캐멀케이스(CamalCase)
#변수: 2개
#함수(메서드): 설정: +, *, -, //, %
class Calculator():
    #클래스의 멤버: 변수, 메서드
    #메서드를 통해 변수(인스턴스 변수)를 생성 => 클래스를 통해서 객체로 만들면 변수가 메모리에 로드

    #초기화 함수 -> 변수 초기화
    def __init__(self, first, second):
        self.first = first
        self.second = second

    #함수 생성시에 self는 강제(없으면 메모리 참조가 불가능함)
    #self 사용이유: 인스턴스 멤버를 사용하기 위해서
    def setData(self, first, second): #self: Instance 자체
        #인스턴스 생성과 데이터 할당
        self.first = first #메서드의 치역 변수(self.first와 first는 다르다.)
        self.second = second

    def printData(self):
        print(f'first: {self.first}, second: {self.second}')

    def add(self):
        return self.first + self.second

    def sub(self):
        return self.first - self.second
    
    def mul(self):
        return self.first * self.second
    
    def div(self):
        return self.first / self.second

In [3]:
#클래스의 상속: 새로운 클래스를 만든다.
#상속 => 기존 클래스의 멤버들을 받아서 내것으로 사용
#오버라이딩 => 메서드를 수정해서 사용, 처리 블록을 수정해서 사용
#MoreFourCal: 새로운 클래스 정의 => pow 제곱을 구해주는 함수를 추가, div 메서드 수정
class MoreFourCalculator(Calculator):
    # pass
    def pow(self):
        return self.first**self.second
    
    #오버라이딩: 함수의 이름과 매개변수는 그대로 유지하고 => 처리부분만 수정해서 정의
    def div(self):
        # return super().div() #Calculator div 메서드 호출
        if self.second == 0:
            return 0
        return self.first / self.second


In [4]:
#cal1 = MoreFourCalculator : 에러 => 생성자 호출
cal1 = MoreFourCalculator(3, 0)

In [5]:
type(cal1)

__main__.MoreFourCalculator

In [6]:
cal1.printData()

first: 3, second: 0


In [7]:
cal1.pow()

1

In [8]:
cal1.div()

0

# 모듈, 패키지

In [9]:
import mod.mod2

mod.mod2 실행 시작
mod.mod2 실행 끝


# 표준모듈

In [10]:
import datetime

In [11]:
day1 = datetime.date(2026,12,25)

print(day1, type(day1))

2026-12-25 <class 'datetime.date'>


In [12]:
day2 = datetime.date(2026,6,26)

day1 - day2
print(day1 - day2)

182 days, 0:00:00


In [13]:
print(day1.year, day1.month, day1.day)

2026 12 25


In [14]:
import time

In [15]:
time.time()

1782461505.610653

In [16]:
lt = time.localtime()

print(lt)
print(lt.tm_year, lt.tm_mon, lt.tm_mday)

time.struct_time(tm_year=2026, tm_mon=6, tm_mday=26, tm_hour=17, tm_min=11, tm_sec=45, tm_wday=4, tm_yday=177, tm_isdst=0)
2026 6 26


In [17]:
time.ctime()

'Fri Jun 26 17:11:45 2026'

In [18]:
#난수
import random as r

In [19]:
r.random()

0.436014267065688

In [20]:
int(r.random()*10+1) #0이상 10미만 실수 반환
int(r.random()*45+1) #1이상 45미만 실수 반환


6

In [21]:
r.randint(1, 46)

14

In [22]:
#난수를 이용해서 리스트 생성
list_scores = []
for s in range(0, 10):
    list_scores.append(r.randint(60, 100))

print(list_scores)

[96, 93, 69, 83, 73, 66, 78, 67, 97, 92]


In [23]:
#리스트에 있는 숫자 무작위 선택
r.choice(list_scores)

66

In [24]:
#리스트에 있는 숫자 중 3개 무작위 선택
r.sample(list_scores, 3)

[66, 93, 78]

In [25]:
import os

#시스템 환경 정보 출력
os.environ

environ{'COMMAND_MODE': 'unix2003',
        'DISPLAY': '/var/run/com.apple.launchd.CpjGeB9ASU/org.xquartz:0',
        'FPATH': '/Users/shinsunbin/.oh-my-zsh/plugins/git:/Users/shinsunbin/.oh-my-zsh/functions:/Users/shinsunbin/.oh-my-zsh/completions:/Users/shinsunbin/.oh-my-zsh/cache/completions:/opt/homebrew/share/zsh/site-functions:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.9/functions',
        'HOME': '/Users/shinsunbin',
        'HOMEBREW_CACHE': '/tmp/shinsunbin/Homebrew/Caches',
        'HOMEBREW_CELLAR': '/opt/homebrew/Cellar',
        'HOMEBREW_PREFIX': '/opt/homebrew',
        'HOMEBREW_REPOSITORY': '/opt/homebrew',
        'HOMEBREW_TEMP': '/tmp/shinsunbin/Homebrew/Temp',
        'INFOPATH': '/opt/homebrew/share/info:',
        'JAVA_HOME': '/Users/shinsunbin/Library/Java/JavaVirtualMachines/azul-17.0.7/Contents/Home',
        'LANG': 'C.UTF-8',
        'LESS': '-R',
        'LOGNAME': 'shinsunbin',
        'LSCOLORS': 'Gxfxcxdxbxegedab

In [26]:
os.getcwd()

'/Users/shinsunbin/Documents/GitHub/shieldus_education'

In [27]:
os.mkdir('test')

In [28]:
os.rmdir('test')

In [29]:
#json 파일 읽기
import json

with open('data.json', 'r', encoding='utf-8') as f:
    #str(json) => list(dict):object
    data = json.load(f)
    print(data, type(data)) #[]을 없애고 {}만 남으면 {} 상태로 key, values를 결과로 출력한다.

[{'name': 'COOL', 'age': 25}] <class 'list'>


In [30]:
#list => str
json_str_data = json.dumps(data)
print(json_str_data, type(json_str_data))

[{"name": "COOL", "age": 25}] <class 'str'>


# 외부모듈

In [31]:
!pip install numpy pandas

In [32]:
import numpy as np

#ndarray: numpy의 배열
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [33]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [34]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
#일련번호로 된 배열 생성
# seq1 = np.arange(0, 11)
seq1 = np.arange(0, 11, 2)
print(seq1)

[ 0  2  4  6  8 10]


In [37]:
#지정된 범위 안에서 동일한 간격으로 숫자를 생성
linspace = np.linspace(1, 10, 4)
print(linspace)

[ 1.  4.  7. 10.]


In [38]:
#속성확인
list_temp = [
    [1,2,3],
    [4,5,6]
]
arr1 = np.array(list_temp)

In [39]:
print(arr1)
print(arr1.shape) #배열의 사이즈: (행, 열)
print(arr1.ndim) #배열의 차원
print(arr1.size) #전체 요소의 개수
print(arr1.dtype) #데이터의 타입


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [40]:
#배열의 인덱싱과 슬라이싱 => List와 같다
arr2 = np.array([10, 20, 30, 40])

print(arr2[2])
print(arr2[-1])

30
40


In [41]:
print(arr1)
print(arr1[0], type(arr1[0]))
print(arr1[1][2])

[[1 2 3]
 [4 5 6]]
[1 2 3] <class 'numpy.ndarray'>
6


In [42]:
arr3 = np.array([10, 20, 30, 40, 50])

print(arr3[:])
print(arr3[1:4])
print(arr3[1:])
print(arr3[:4])

[10 20 30 40 50]
[20 30 40]
[20 30 40 50]
[10 20 30 40]


In [43]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
arr[ 0:2 , 1: ]

array([[2, 3],
       [5, 6]])

In [45]:
#배열의 연산: +, *, **
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + 10)
print(arr1 * 10)
print(arr2 ** 2)
print(arr1 + arr2)
print(arr1 * arr2)

[11 12 13]
[10 20 30]
[16 25 36]
[5 7 9]
[ 4 10 18]


In [46]:
#배열의 구조 변경: 1->2, 2-1
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

#1->2
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr, reshaped_arr.shape)

(6,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [47]:
#2->1
flated_arr = reshaped_arr.flatten()
print(flated_arr)

[1 2 3 4 5 6]


In [48]:
#필터링
arr = np.array([1,2,3,4,5,6])
filtering_arr = arr[arr>3]
print(filtering_arr)

[4 5 6]


In [49]:
#난수를 생성해서 배열 생성
ran_arr1 = np.random.rand(10)
print(ran_arr1)

[0.47101479 0.0146323  0.85964306 0.28349187 0.6665738  0.0177802
 0.00378847 0.86165779 0.30159424 0.61338504]


In [50]:
ran_arr2 = np.random.randint(1, 46, size=(5, 6))
print(ran_arr2)

[[22  7  4 43 30 28]
 [ 9  5 28 24 44 24]
 [ 1 13 22  2 28 32]
 [10 21 42 32 20 34]
 [ 2  9 32 37 44 44]]


# Pandas

In [51]:
import pandas as pd

In [52]:
#DataFrame: 2차원 형식의 표 모양으로 데이터 구조를 생성
data = {
    'Name': ['cool', 'hot', 'king'],
    'Age': ['20', '25', '23']
}

df = pd.DataFrame(data)
print(type(df))

<class 'pandas.DataFrame'>


In [53]:
print(df)

   Name Age
0  cool  20
1   hot  25
2  king  23


In [54]:
df.head(2)

,Name,Age
0,cool,20
1,hot,25


In [55]:
df.shape

(3, 2)

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str  
 1   Age     3 non-null      str  
dtypes: str(2)
memory usage: 180.0 bytes


In [57]:
#기초 통계 지표(숫자 데이터)
df.describe()

,Name,Age
count,3,3
unique,3,3
top,cool,20
freq,1,1


In [58]:
df['Age'].sum()
df['Age'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [59]:
data = {
    'name': ['kevin', 'son', 'messi'],
    'age': [35, 34, 39],
    'score': [15, 23, 85]
}
df = pd.DataFrame(data)

In [60]:
df

,name,age,score
0,kevin,35,15
1,son,34,23
2,messi,39,85


In [61]:
#새로운 DataFrame
df[['name', 'score', 'age']]

,name,score,age
0,kevin,15,35
1,son,23,34
2,messi,85,39


In [64]:
df['passed'] = df['score'] >= 70

df

,name,age,score,passed
0,kevin,35,15,False
1,son,34,23,False
2,messi,39,85,True


In [65]:
df[['name', 'passed']]

,name,passed
0,kevin,False
1,son,False
2,messi,True


In [66]:
df

,name,age,score,passed
0,kevin,35,15,False
1,son,34,23,False
2,messi,39,85,True


In [75]:
#변수값을 변경
df.loc[2, 'score'] = 68

In [76]:
df

,name,age,score,passed
0,kevin,35,15,False
1,son,34,23,False
2,messi,39,68,True


In [77]:
df['passed'] = df['score'] >= 70

In [78]:
df

,name,age,score,passed
0,kevin,35,15,False
1,son,34,23,False
2,messi,39,68,False


In [ ]:
#점수를 NaN (None) 처리하기
df.loc[1, 'score'] = None

In [80]:
df

,name,age,score,passed
0,kevin,35,15.0,False
1,son,34,NaN,False
2,messi,39,68.0,False


In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    3 non-null      str    
 1   age     3 non-null      int64  
 2   score   2 non-null      float64
 3   passed  3 non-null      bool   
dtypes: bool(1), float64(1), int64(1), str(1)
memory usage: 207.0 bytes


In [83]:
df

,name,age,score,passed
0,kevin,35,15.0,False
1,son,34,NaN,False
2,messi,39,68.0,False


In [82]:
df.describe()

,age,score
count,3.000000,2.000000
mean,36.000000,41.500000
std,2.645751,37.476659
min,34.000000,15.000000
25%,34.500000,28.250000
50%,35.000000,41.500000
75%,37.000000,54.750000
max,39.000000,68.000000


In [84]:
df.isnull()

,name,age,score,passed
0,False,False,False,False
1,False,False,True,False
2,False,False,False,False


In [85]:
df['score'] = df['score'].fillna(100)

In [86]:
df

,name,age,score,passed
0,kevin,35,15.0,False
1,son,34,100.0,False
2,messi,39,68.0,False


In [ ]:
df.to_csv('output.csv', index=False)

In [ ]:
data_csv = pd.read_csv('output.csv')

   Unnamed: 0   name  age  score  passed
0           0  kevin   35   15.0   False
1           1    son   34  100.0   False
2           2  messi   39   68.0   False


In [90]:
data_csv

,Unnamed: 0,name,age,score,passed
0,0,kevin,35,15.0,False
1,1,son,34,100.0,False
2,2,messi,39,68.0,False
